baseURL = "https://www.moclojer.com"
languageCode = "en-us"
title = "moclojer - Open Source Clojure Projects"
theme = "moclojer"

[module]
  [module.hugoVersion]
    extended = true
    min = "0.114.0"

[[module.imports]]
  path = "github.com/hugomods/mermaid"


[[module.imports]]
  path = 'github.com/hugomods/images'

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
  [markup.highlight]
    anchorLineNos = true
    codeFences = true
    guessSyntax = false
    hl_Lines = ''
    hl_inline = false
    lineAnchors = ''
    lineNoStart = 1
    lineNos = true
    lineNumbersInTable = true
    noClasses = true
    noHl = false
    style = 'dracula'
    tabWidth = 4

[params]
  # Configure Google Tag Manager ID (which can include Google Analytics)
  google_tag_manager_id = "GTM-XXXXXXX"

  [params.mermaid]
    js_url = 'https://cdn.jsdelivr.net/npm/mermaid@latest/dist/mermaid.esm.min.mjs'

  [params.homepage]
    show_contact_box = true # show / hide the contaxt box on the homepage
    show_services_button = true  # show / hide the "view all services" button

  [params.logo]
    mobile = "images/logo/logo-moclojer-icon.png"
    mobile_height = "36px"
    desktop = "images/logo/logo-moclojer-icon.png"
    desktop_height = "36px"
    alt = "moclojer - Open Source Clojure Projects"

  [params.fonts]
    # sets the google font link in layouts/partials/google-fonts.html
    google_fonts = 'https://fonts.googleapis.com/css2?family=Playfair+Display:wght@600&family=Source+Sans+Pro:wght@400;700&display=swap'
    heading = "Playfair Display"
    base = "Source Sans Pro"

  [params.colors]
    primary = "#FF009E"
    black = "#22212C"
    white = "#ffffff"
    white_offset = "#F8F8F2"
    grey = "#454158"

  [params.seo]
    meta_twitter_site = "@moclojer"
    meta_twitter_creator = "@moclojer"
    meta_og_image = "https://repository-images.githubusercontent.com/462693523/bba1dade-cd7f-4101-954a-f37c34097f35"

  [params.team]
    summary_large_truncate = 120  # How many characters to include in the summary of the team bios (large layout) before truncating

  [params.footer]
    copyright_text = 'made with 💜 and clojure by design'

[menu]
  # Main Menu
  [[menu.main]]
    name = "Projects"
    url = "/projects/"
    weight = 1
  [[menu.main]]
    name = "Documentation"
    url = "https://docs.moclojer.com/"
    weight = 2
  [[menu.main]]
    name = "Features"
    url = "/features/"
    weight = 3
  [[menu.main]]
      name = "Team"
      url = "/team/"
      weight = 4
  [[menu.main]]
      name = "Blog"
      url = "/blog/"
      weight = 5
  [[menu.main]]
      name = "About"
      url = "/about/"
      weight = 6
  [[menu.main]]
    name = "Login"
    url = "https://app.moclojer.com/"
    weight = 7

  # Footer Menu
  [[menu.footer]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.footer]]
    name = "Projects"
    url = "/projects/"
    weight = 2
  [[menu.footer]]
    name = "Careers"
    url = "/about/careers/"
    weight = 3
  [[menu.footer]]
    name = "Blog"
    url = "/blog/"
    weight = 4
  [[menu.footer]]
    name = "About"
    url = "/about/"
    weight = 5
  [[menu.footer]]
    name = "Terms of Use"
    url = "/about/term-of-use/"
    weight = 6
