[build]
publish = "public"
command = "hugo mod tidy && hugo --gc --minify"

[context.production.environment]
HUGO_VERSION = "v0.126.1"
HUGO_ENV = "production"
HUGO_ENABLEGITINFO = "true"
GO_VERSION = "1.22.3"

[[plugins]]
  package = "@netlify/plugin-lighthouse"

  # optional, deploy the lighthouse report to a path under your site
  [plugins.inputs.audits]
    output_path = "reports/lighthouse.html"
